### ISSUE TITLE
3MF broken

### ISSUE THREAD

**Issue by roamingthings** [nevermore3d/refiller_spoons#1]
The file seems to be broken. Is it possible to upload a fixed version?
<img width="480" alt="Screenshot 2024-02-25 at 08 17 51" src="https://github.com/nevermore3d/refiller_spoons/assets/902291/2bb74557-7dc2-4219-96a6-3447dca0054c">

**Comment by 0ndsk4** [comment]
fixed now?

**Comment by roamingthings** [comment]
<img width="456" alt="Screenshot 2024-02-26 at 13 07 44" src="https://github.com/nevermore3d/refiller_spoons/assets/902291/75b4307c-f4fc-4a22-ac4f-735655272866">
 Yes 👍 
Thank you!
